import { useState } from "react";
import {
  AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent,
  AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { Loader2, AlertTriangle } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { formatCRC } from "@/lib/currency";
import { cancellationOutcome, cancellationFee, POLICY_LINES } from "@/lib/cancellationPolicy";

interface Props {
  booking: {
    id: string;
    start_time?: string | null;
    booking_date: string;
    booking_time?: string | null;
    total_price?: number | null;
    services?: { title?: string | null } | null;
  };
  onCancelled: (bookingId: string) => void;
}

/** The appointment instant, falling back to the date + wall clock when a
 *  booking has no start_time (at-location visits). Mirrors the same fallback
 *  in cancel_own_booking(). */
function startsAt(b: Props["booking"]): Date {
  if (b.start_time) return new Date(b.start_time);
  return new Date(`${b.booking_date}T${(b.booking_time || "00:00:00").slice(0, 8)}`);
}

/**
 * Cancelling is the only change a guest can make on their own. Moving a
 * treatment, a date or a time goes through a person on WhatsApp or email, so
 * nobody reshuffles the room schedule unattended.
 */
export function CancelAppointmentDialog({ booking, onCancelled }: Props) {
  const [open, setOpen] = useState(false);
  const [working, setWorking] = useState(false);

  const { isLate } = cancellationOutcome(startsAt(booking));
  const fee = cancellationFee(booking.total_price, isLate ? 50 : 0);
  const serviceName = booking.services?.title || "your appointment";

  const confirm = async () => {
    setWorking(true);
    try {
      // The window is re-checked on the server; this dialog only previews it.
      // src/integrations/supabase/types.ts is regenerated by hand and does not
      // list cancel_own_booking yet; the cast goes away on the next refresh.
      const { data, error } = await (supabase.rpc as any)("cancel_own_booking", {
        _booking_id: booking.id,
      });
      if (error) throw error;

      const result = (data ?? {}) as { fee_percent?: number; fee_amount?: number };
      // Best effort: a failed email must not leave the guest thinking the
      // cancellation did not go through, because it did.
      supabase.functions
        .invoke("send-booking-notification", { body: { cancelledBookingId: booking.id } })
        .catch(() => {});

      toast.success(
        result.fee_percent
          ? `Appointment cancelled. A ${result.fee_percent}% fee of ${formatCRC(result.fee_amount ?? fee)} applies.`
          : "Appointment cancelled. No charge — we've emailed you the confirmation.",
      );
      onCancelled(booking.id);
      setOpen(false);
    } catch (e: any) {
      toast.error(e?.message || "We could not cancel that. Please contact us on WhatsApp.");
    } finally {
      setWorking(false);
    }
  };

  return (
    <>
      <Button
        variant="outline"
        size="sm"
        className="self-start sm:self-auto"
        onClick={() => setOpen(true)}
      >
        Cancel appointment
      </Button>

      <AlertDialog open={open} onOpenChange={(o) => !working && setOpen(o)}>
        <AlertDialogContent className="max-w-lg">
          <AlertDialogHeader>
            <AlertDialogTitle>Cancel {serviceName}?</AlertDialogTitle>
            <AlertDialogDescription asChild>
              <div className="space-y-3 text-left">
                {isLate ? (
                  <div className="flex gap-2.5 rounded-lg border border-destructive/30 bg-destructive/5 p-3">
                    <AlertTriangle className="h-4 w-4 shrink-0 text-destructive mt-0.5" />
                    <p className="text-sm text-foreground">
                      This is <strong>within 24 hours</strong> of your appointment, so{" "}
                      <strong>50% of the total{fee > 0 ? ` (${formatCRC(fee)})` : ""}</strong> will be
                      charged to the card on file.
                    </p>
                  </div>
                ) : (
                  <p className="text-sm">
                    You are more than 24 hours ahead, so there is{" "}
                    <strong>no charge</strong> for cancelling.
                  </p>
                )}

                <div className="rounded-lg bg-muted/50 p-3">
                  <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground mb-1.5">
                    Cancellation policy
                  </p>
                  <ul className="space-y-1 text-xs leading-relaxed">
                    {POLICY_LINES.map((line) => <li key={line}>· {line}</li>)}
                  </ul>
                </div>
              </div>
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel disabled={working}>Keep appointment</AlertDialogCancel>
            <AlertDialogAction
              onClick={(e) => { e.preventDefault(); confirm(); }}
              disabled={working}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              {working && <Loader2 className="h-4 w-4 mr-2 animate-spin" />}
              Cancel appointment
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  );
}
