// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Strip a stray BOM (U+FEFF) / zero-width space or surrounding whitespace that can
// sneak into env values (e.g. a key pasted from a UTF-8-BOM file / PowerShell).
// Such a char is illegal in an HTTP header and makes fetch throw "String contains
// non ISO-8859-1 code point", which silently breaks every authenticated request
// (login, signout, data reads...) while the rest of the page still loads.
const clean = (v) => (v ?? "").replace(/[﻿​]/g, "").trim();

const SUPABASE_URL = clean(import.meta.env.VITE_SUPABASE_URL);
const SUPABASE_PUBLISHABLE_KEY = clean(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
